### ISSUE TITLE
Margin problem

### ISSUE THREAD

**Issue by andriykrypov** [ajbogh/video-js-html5Thumbnails#1]
The plugin does not work properly with the addition of an indent for the player (for example margin-left: 1000px;). Plugin starts its life from the beginning of the browser window only (cant add same margin as video player have). Accordingly, while a thumbnail can not match too, and at the end of the width of the player (plugin) disappears altogether.

You can add margin-left:1000px (for example) to see this problem.

I hope the creator of the plugin will fix this bug. I really liked your work, 
With best wishes, the user

**Comment by ajbogh** [comment]
Thanks @andriykrypov. I will work on a fix for this tonight. Keep an eye out for an update soon.

**Comment by andriykrypov** [comment]
Thanks. Besides, I think maybe someone wants to use a separate video for thumbnails (which is smaller in size for example) It would be nice to add an option that would allow the user to select a video thumbnail directly. I'm sure it would help someone

**Comment by ajbogh** [comment]
@andriykrypov, nice catch on this bug! I have to modify the function that calculates the mouse position to get this working right. It's not a big deal, it'll just take another day or so (if I'm lucky). 

I've also added gulp and jshint to the project to allow someone to run a local server and double-check the Javascript syntax. It has allowed me to find a couple of minor mistakes.

**Comment by ajbogh** [comment]
Fixed in 1074d438683f2553c07dfb1f8bb1cab4db2e8ff2.

**Comment by andriykrypov** [comment]
Great! Thanks.
